// <auto-generated />
using System;
using Fincore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fincore.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005172728_MakeRFQFieldsNullable")]
    partial class MakeRFQFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fincore.Domain.Entity.FinalizedQuotation", b =>
                {
                    b.Property<int>("FinalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinalId"));

                    b.Property<DateTime?>("FinalizedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.HasKey("FinalId");

                    b.HasIndex("QuotationId")
                        .IsUnique();

                    b.HasIndex("RFQId")
                        .IsUnique();

                    b.ToTable("FinalizedQuotations");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQ", b =>
                {
                    b.Property<int>("RFQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RFQId"));

                    b.Property<DateTime?>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDateofBid")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQLineNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReqDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReqQty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RFQId");

                    b.HasIndex("UserId");

                    b.ToTable("RFQs");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<string>("RFQLineNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReqDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReqQty")
                        .HasColumnType("int");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("RFQId");

                    b.ToTable("RFQItems");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQQuotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotationId"));

                    b.Property<string>("BidNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QuotedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("QuotationId");

                    b.HasIndex("RFQId");

                    b.HasIndex("VendorId");

                    b.ToTable("RFQQuotations");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.Role", b =>
                {
                    b.Property<int>("rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rid"));

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rid");

                    b.ToTable("role");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.User", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rid")
                        .HasColumnType("int");

                    b.HasKey("eid");

                    b.HasIndex("rid");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.VendorRFQMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RFQId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RFQId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorRFQMappings");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.FinalizedQuotation", b =>
                {
                    b.HasOne("Fincore.Domain.Entity.RFQQuotation", "RFQQuotation")
                        .WithOne("FinalizedQuotation")
                        .HasForeignKey("Fincore.Domain.Entity.FinalizedQuotation", "QuotationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fincore.Domain.Entity.RFQ", "RFQ")
                        .WithOne("FinalizedQuotation")
                        .HasForeignKey("Fincore.Domain.Entity.FinalizedQuotation", "RFQId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("RFQQuotation");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQ", b =>
                {
                    b.HasOne("Fincore.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQItem", b =>
                {
                    b.HasOne("Fincore.Domain.Entity.RFQ", "RFQ")
                        .WithMany("RFQItems")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RFQ");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQQuotation", b =>
                {
                    b.HasOne("Fincore.Domain.Entity.RFQ", "RFQ")
                        .WithMany("RFQQuotations")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fincore.Domain.Entity.User", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.User", b =>
                {
                    b.HasOne("Fincore.Domain.Entity.Role", "role")
                        .WithMany()
                        .HasForeignKey("rid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("role");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.VendorRFQMapping", b =>
                {
                    b.HasOne("Fincore.Domain.Entity.RFQ", "RFQ")
                        .WithMany("RFQVendors")
                        .HasForeignKey("RFQId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fincore.Domain.Entity.User", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RFQ");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQ", b =>
                {
                    b.Navigation("FinalizedQuotation");

                    b.Navigation("RFQItems");

                    b.Navigation("RFQQuotations");

                    b.Navigation("RFQVendors");
                });

            modelBuilder.Entity("Fincore.Domain.Entity.RFQQuotation", b =>
                {
                    b.Navigation("FinalizedQuotation");
                });
#pragma warning restore 612, 618
        }
    }
}
